### PR TITLE
Programatically click on the calendar-link on pageload

### PR DESCRIPTION
**Pull request by Tejpbit**
this is best solution

### CODE REVIEW

**Comment by Dr-Horv** [comment]
Why is this needed?

**Comment by Tejpbit** [comment]
I tried to implement the feature as it was meant to be from the beginning. @lindskogen described to me how it was weirdly annoying to implement. This is just a workaround.

It's not really needed. It's just to finalise the UI.

**Comment by Dr-Horv** [comment]
Ah, better than nothing. :)

**Comment by lindskogen** [comment]
Fine for now.. Merge!

**Pull request merged**
